services:
  discarr:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env.local
        required: false
      - path: packages/api/.env.local
        required: true
