services:
  discarr:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env.local
        required: false
      - path: packages/api/.env.local
        required: true
#     volumes:
#       - db-data:/var/lib/postgresql/data
# ports:
#   - "3000:3000"
#   - "5432:5432"

# volumes:
#   db-data:
