packages:
  - packages/*
  - configs/*
catalog:
  '@electric-sql/pglite': ^0.2.17
  '@eslint/compat': ^1.2.7
  '@eslint/js': ^9.23.0
  '@radix-ui/themes': ^3.1.3
  '@stitches/react': ^1.2.8
  '@storybook/addon-essentials': ^8.2.9
  '@storybook/addon-interactions': ^8.2.9
  '@storybook/addon-links': ^8.2.9
  '@storybook/addon-themes': ^8.2.9
  '@storybook/blocks': ^8.2.9
  '@storybook/react': ^8.2.9
  '@storybook/react-vite': ^8.2.9
  '@storybook/test': ^8.2.9
  '@tanstack/react-query': ^4.18.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.0.1
  '@trpc/client': ^10.45.2
  '@trpc/react-query': ^10.45.2
  '@trpc/server': ^10.45.2
  '@types/cors': ^2.8.17
  '@types/node': ^22.13.14
  '@types/node-cron': ^3.0.11
  '@types/react': ^18.3.3
  '@types/react-dom': ^18.3.0
  '@vitejs/plugin-react-swc': ^3.5.0
  cors: ^2.8.5
  discord.js: ^14.18.0
  dotenv: ^16.4.7
  drizzle-kit: ^0.30.6
  drizzle-orm: ^0.41.0
  drizzle-zod: ^0.5.1
  eslint: ^9.23.0
  eslint-config-prettier: ^10.1.1
  eslint-plugin-react: ^7.37.4
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.19
  eslint-plugin-turbo: ^2.4.4
  globals: ^15.9.0
  husky: ^9.1.5
  jsdom: ^25.0.0
  lint-staged: ^15.2.10
  msw: ^1.3.4
  msw-storybook-addon: ^1.10.0
  msw-trpc: ^1.3.4
  node-cron: ^3.0.3
  openapi-fetch: ^0.13.4
  postgres: ^3.4.4
  prettier: ^3.3.3
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router: ^7.1.3
  storybook: ^8.2.9
  superjson: ^2.2.1
  tsx: ^4.19.1
  turbo: ^2.1.2
  typescript: ^5.6.2
  typescript-eslint: ^8.28.0
  vite: ^5.4.1
  vitest: ^2.0.5
  winston: ^3.17.0
  zod: ^3.24.3

catalogs:
  msw1:
    msw: ^1.3.4
    msw-storybook-addon: ^1.10.0
    msw-trpc: ^1.3.4
