version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

    env_file: .env.development

    ports:
      - '5432:5432'

volumes:
  postgres-data:
